### ISSUE TITLE
Browser compatible version

### ISSUE THREAD

**Issue by edludke** [alpacahq/alpaca-trade-api-js#105]
This is more of a request than an actual issue with the existing code. And quite frankly a lot of this is new territory for me so please forgive me if my ignorance is showing. But is there a way to make this run client-side in the browser instead of server-side in nodejs? I was hoping to create some live graphs, dials and knobs based upon the live streaming data. I imagine I can write my own code interacting with the APIs directly but... sure would be nice to leverage the work already put into a framework like this. TIA! -Ed

**Comment by edludke** [comment]
@clwillingham what am I doing wrong?

Uncaught ReferenceError: require is not defined
    at alpaca-trade-api.js:5

Installed your version of the package. Got it to work under NPM. Then made some minor changes to look like so:

`<!DOCTYPE HTML>
<html>
  <head>

    <script src="node_modules/@alpacahq/alpaca-trade-api/lib/alpaca-trade-api.js"></script>

  </head>
  <body>

    <p>Before the script...</p>

    <script>
//      const Alpaca = require('@alpacahq/alpaca-trade-api');

      const alpaca = new Alpaca({
        keyId: 'XXX',
        secretKey: 'YYY',
        paper: true
      });

      async function printAccount() {
        const account = await alpaca.getAccount();
        console.log(account);
      }

      printAccount();
    </script>

    <p>...After the script.</p>

  </body>
</html>`

...but Chrome doesn't seem to like `require` at all anywhere. Thanks for your work on this!!

**Comment by clwillingham** [comment]
If your writing a raw html script without a compiler like webpacker or browserify, then you might want to look into just using the `AlpacaCORS` api shown in the example [here](https://github.com/alpacahq/alpaca-trade-api-js/blob/master/examples/long-short-browser/browser-trader.html)
Looking through the source code it looks like its a mostly complete version of the regular Alpaca API but with a few differences (like instead of having a boolean to define weather or not your using the Paper API endpoint, you directly set the API to use the Paper API). 
I did also add to my fork a webpacker compiler that lets you directly use the main Alpaca API within the browser (example available [here](https://github.com/clwillingham/alpaca-trade-api-js/blob/master/examples/long-short-browser/browser-trader.html)).
I should note that something changed in the last few days in the back-end of the market data api and getBars now throws a CORS error (getAsset and getAssets does not though). before whatever backend cors policy change they made this week, I was able to get market data from the browser using the existing API though.

**Comment by edludke** [comment]
Yes, I was doing that originally (raw html script without a compiler when I posted my question) but continued digging and ended up finding and using Browserify to get past the "require" issue. And that actually allowed me to connect & pull bars - but now I'm hitting an issue where the browser's native web socket is required instead of what's used in nodejs. Surprised/disappointed the compiler doesn't "fix" that, but I'll start digging around to solve that next. I'll also dig into the "browser-trader.html" example you pointed me to. Maybe that's a shorter path to where I'm trying to get. And again, cannot express enough how much the help and your work here is appreciated. With luck, time and determination, I'll skill up enough to contribute to this or other efforts myself. In the meantime, it's just great to have someone else out there ;-)
