### ISSUE TITLE
Incorrect data returned by getBars function

### ISSUE THREAD

**Issue by ProjectAGM** [alpacahq/alpaca-trade-api-js#43]
Upon calling the getBars function with a timeframe of "1Min", and options specifying a time period of 250 Minutes (with { start: _250 minutes ago_, end: _now_ } ), it returns a seemingly random amount of bars. (In this case: 35 Bars) 
There seems to be no logical explanation on this happening, and I haven't been able to determine any errors on my side.

**Comment by ttt733** [comment]
This is because getBars refers to IEX data, which is not complete market data. There may be many minutes in any given range in which no trades occurred for a particular symbol on IEX, and therefore IEX will not return data for those minutes. If you have some suggestions as to how the handling of such cases could be improved, please feel free to make note of them or open a PR.

**Comment by suvodeep-pyne** [comment]
I observed something which was a bit concerning.

For example, on April 17 2020, `AAPL` traded for `53.8M` shares by Volume as shown on [nasdaq.com](https://www.nasdaq.com/market-activity/stocks/aapl) and also reported by Yahoo Finance.

However, Alpaca API reports *more than 3 times*the Volume on the same day as `189.5M`.
```
        {
            "t": 1587096000,
            "o": 284.69,
            "h": 286.945,
            "l": 276.86,
            "c": 282.74,
            "v": 189543675
        },
```
I just wanted to understand if anybody else has seen these issues. Or please let me know if I'm making a mistake. The API request I used is
```
GET https://data.alpaca.markets/v1/bars/1D?symbols=AAPL&limit=1000
```
