### ISSUE TITLE
Issue with how multiple websockets connections (and potentially sessions) are handled

### ISSUE THREAD

**Issue by drixie** [alpacahq/alpaca-trade-api-js#51]
I initially connected to Websockets in one project and it worked fine. I wanted to connect from another project using the same credentials, however authentication does not work. 

Now I understand connections are limited to a single client, but the connection is not working from my second project even after calling client.disconnect() from my first project. Using onStateChange prints the following to the console: 
```
State changed to authenticating
State changed to disconnected
```

Using the websockets example code from Polygon worked fine and resulted in a connection, which successfully authenticates, and then disconnects both the current connection and first project's connection. The good thing about this is that it prints a helpful error message to the console: 
`Status Update: Maximum number of connections exceeded`
I can then reconnect again with no problems
Sidenote: The Polygon direct websocket connection still disconnects even when you set usePolygon to false on the Alpaca authentication object. 

I believe there is an issue with how multiple connections are handled in this repo. It prevents connection from another codebase (even after the first one is disconnected), and does not provide any helpful error message

**Comment by philgapp** [comment]
Helpful info, thanks for the share! I haven't started using the websockets yet but I will keep this issue in mind and see what I can do to help in the next couple of weeks (assuming I don't get busy elsewhere in this code!).

**Comment by shlomikushchi** [comment]
Hi Drixie, 
first of all thanks for the info
I'm not sure I understand the issue, so I cannot help resolve it until I do.
let's try to make me understand everything
first of all it's important to understand we could use either the polygon ws or the alpaca data ws
we have a redundancy. 
the alpaca data ws is a new feature currently in beta, and you have to be in the test group in order to be allowed to use that ( it is not documented in this repo and and I will change that)
so first question - are you in the test group for this data api?

the polygon ws - should work exactly as it has so far. ( if I understand correctly you don't have an issue with that)

now, as you mentioned the connections a re limited. 
meaning - you can't connect to the data service with more than one ws ( in the same node instance or in another one)

I didn't understand exactly what you mean when you say that you can't connect from one project but you can from the other... is it the same code? are you using the same websockets?

let me know and we will try to understand what's going on .

**Comment by kevinsherman** [comment]
FWIW, i requested access to the test group, and was told "it's open to all as of today"... however, I am not receiving any updates when I connect as noted in the readme. I *can* call getAccount(), get Orders(), etc. - but i'm not getting quote/trade updates from the websocket (using exact code from readme... modified only with my keyId/secretKey).

**Comment by shlomikushchi** [comment]
try the example code https://github.com/alpacahq/alpaca-trade-api-js/blob/master/examples/long-short.js

**Comment by shlomikushchi** [comment]
@kevinsherman please install the udpated version and try again
install directly from github
