### ISSUE TITLE
Bracket Order: Cannot get order status after entry is filled.

### ISSUE THREAD

**Issue by immanuelx2** [alpacahq/alpaca-trade-api-js#87]
Before a bracket entry is filled, everything seems to work fine. I can see the order with the following code:
`getOrders({ status: 'open', limit: 100, nested: true })`

However, **once the bracket entry order is filled** there seems to be **two issues**:

First issue:
`nested: true` **does not return any results at all**, even though I still have two open orders (take_profit and stop_loss). I understand they are no longer nested, but I'd assume they should still be returned otherwise it looks like I have no open orders at all.

Second issue:
`nested: false`, lets me see the take_profit order, but I **cannot see the stop_loss order** whether I use `nested: true` or not.

**Comment by shlomikushchi** [comment]
Hi,
When created the status cannot be New for all 3 (basically one is opened at a time). The other orders are held
![image](https://user-images.githubusercontent.com/7924802/92497298-d8897e80-f201-11ea-9f1e-c532d333a118.png)

this is why you see 1 open order. basically the amount of shares is allocated per order, and once it's allocated it cannot be added to another order (that is by design)
take a look at your account in the website, see how status changes when orders are filled

**Comment by immanuelx2** [comment]
Hi @shlomikushchi thanks for the quick response.

That makes sense but it seems like the API has trouble retrieving _held_ orders after the bracket entry is filled, and because of that these issues exist. The Alpaca dashboard shows me held orders (screenshot below), but the API does not.

`nested: true` will return **zero results** while `nested: false` only returns the take_profit, so there doesn't seem to be any way for me to check the full status (take_profit & stop_loss) of a bracket order that has it's entry filled, with the API.

![image](https://user-images.githubusercontent.com/53500318/92514322-b121ba00-f1df-11ea-983d-bc80db9db8a7.png)

**Comment by shlomikushchi** [comment]
Hi, sorry for the delay
I checked it, and you are right.
what you can do in the mean time - when you fill a bracket order you get in response all 3 orders.
they include ids.
you could save those ids and then you could do:
`api.getOrder()` with the id you got for `createOrder()` for all 3. that includes the held order:
![image](https://user-images.githubusercontent.com/7924802/92761400-51234300-f39a-11ea-8956-fb5dbeab01b4.png)

also, you could submit this issue to the Alpaca core forum (this issue, if a bug or by design is not related to this package but to the core api) here: https://forum.alpaca.markets
